bash train_all.sh
bash train_lmsyschat.sh
bash train_tulu2mix-code_alpaca.sh
bash train_tulu2mix-cot.sh
bash train_tulu2mix-flan_v2.sh
bash train_tulu2mix-gpt4_alpaca.sh
bash train_tulu2mix-oasst1.sh
bash train_tulu2mix-open_orca.sh
bash train_tulu2mix-science.sh
bash train_tulu2mix-sharegpt.sh
bash train_tulu2mix-wizardlm.sh
bash train_ultrachat.sh
bash train_ultrainteract.sh
bash train_wildchat-gpt-4-0125-preview.sh
