bash gantry/llama2_loo/train_all.sh
#bash gantry/llama2_loo/train_lmsyschat.sh
#bash gantry/llama2_loo/train_tulu2mix-code_alpaca.sh
bash gantry/llama2_loo/train_tulu2mix-cot.sh
bash gantry/llama2_loo/train_tulu2mix-flan_v2.sh
bash gantry/llama2_loo/train_tulu2mix-gpt4_alpaca.sh
bash gantry/llama2_loo/train_tulu2mix-oasst1.sh
bash gantry/llama2_loo/train_tulu2mix-open_orca.sh
bash gantry/llama2_loo/train_tulu2mix-science.sh
#bash gantry/llama2_loo/train_tulu2mix-sharegpt.sh
bash gantry/llama2_loo/train_tulu2mix-wizardlm.sh
bash gantry/llama2_loo/train_ultrachat.sh
bash gantry/llama2_loo/train_ultrainteract.sh
bash gantry/llama2_loo/train_wildchat-gpt-4-0125-preview.sh
